import type { Metadata } from "next";
import "./globals.css";
import "../../public/fonts/gilroy/stylesheet.css";
import "../../public/fonts/involve/stylesheet.css";
import "../../public/fonts/helvetica/stylesheet.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {children}
        <div id="modal-root"></div>
      </body>
    </html>
  );
}
